import type { menuButtonIdsType } from "../types/menuButtonIdsType";

export const menuButtonIds = {
    mainMenu: {
        paths: ["mainMenu"],
        supportedModes: {
            advanced: false,
            simple: false,
        },
        buttons: {
            editorStick: {
                displayName: "Editor Stick",
                icon: "textures/items/stick",
                deprecated: true,
                experimental: false,
                unused: false,
                upcoming: false,
                functional: true,
                advanced: false,
                defaultButtonIndex: 0,
            },
            editorStickMenuB: {
                displayName: "Editor Stick Menu B",
                icon: "textures/items/stick",
                deprecated: true,
                experimental: false,
                unused: false,
                upcoming: false,
                functional: true,
                advanced: false,
                defaultButtonIndex: 1,
            },
            editorStickMenuC: {
                displayName: "Editor Stick Menu C",
                icon: "textures/items/stick",
                deprecated: true,
                experimental: false,
                unused: false,
                upcoming: false,
                functional: true,
                advanced: false,
                defaultButtonIndex: 2,
            },
            debugScreen: {
                displayName: "§8Debug Screen§f(§cUnused§f)§b",
                icon: "textures/ui/ui_debug_glyph_color",
                deprecated: true,
                experimental: false,
                unused: true,
                upcoming: false,
                functional: false,
                advanced: false,
                defaultButtonIndex: 3,
            },
            inventoryController: {
                displayName: "Inventory Controller",
                icon: "textures/ui/inventory_icon.png",
                deprecated: true,
                experimental: false,
                unused: false,
                upcoming: false,
                functional: true,
                advanced: false,
                defaultButtonIndex: 4,
            },
            playerDebug: {
                displayName: "Player Debug",
                icon: "textures/ui/debug_glyph_color",
                deprecated: true,
                experimental: false,
                unused: false,
                upcoming: false,
                functional: true,
                advanced: false,
                defaultButtonIndex: 5,
            },
            entityDebug: {
                displayName: "Entity Debug§b",
                icon: "textures/ui/debug_glyph_color",
                deprecated: true,
                experimental: false,
                unused: false,
                upcoming: false,
                functional: true,
                advanced: false,
                defaultButtonIndex: 6,
            },
            playerController: {
                displayName: "Player Controller",
                icon: "textures/ui/controller_glyph_color",
                deprecated: true,
                experimental: false,
                unused: false,
                upcoming: false,
                functional: true,
                advanced: false,
                defaultButtonIndex: 7,
            },
            entityController: {
                displayName: "Entity Controller",
                icon: "textures/ui/controller_glyph_color_switch",
                deprecated: true,
                experimental: false,
                unused: false,
                upcoming: false,
                functional: true,
                advanced: false,
                defaultButtonIndex: 8,
            },
            worldOptions: {
                displayName: "World Options§b",
                icon: "textures/ui/settings_glyph_color_2x",
                deprecated: true,
                experimental: false,
                unused: false,
                upcoming: false,
                functional: true,
                advanced: false,
                defaultButtonIndex: 9,
            },
            dimensionOptions: {
                displayName: "§4Dimension Options§f(§cComing Soon!§f)§b",
                icon: "textures/ui/icon_setting",
                deprecated: true,
                experimental: false,
                unused: false,
                upcoming: true,
                functional: false,
                advanced: false,
                defaultButtonIndex: 10,
            },
            createExplosion: {
                displayName: "Create Explosion",
                icon: "textures/blocks/tnt_side",
                deprecated: false,
                experimental: false,
                unused: false,
                upcoming: false,
                functional: true,
                advanced: false,
                defaultButtonIndex: 13,
            },
            fillBlocks: {
                displayName: "§4Fill Blocks(§cComing Soon!§f)§b",
                icon: "textures/blocks/stone",
                deprecated: true,
                experimental: false,
                unused: false,
                upcoming: true,
                functional: false,
                advanced: false,
                defaultButtonIndex: 14,
            },
            worldDebug: {
                displayName: "§4World Debug§f(§cComing Soon!§f)§b",
                icon: "textures/ui/xyz_axis.png",
                deprecated: true,
                experimental: false,
                unused: false,
                upcoming: true,
                functional: false,
                advanced: false,
                defaultButtonIndex: 15,
            },
            dimensionDebug: {
                displayName: "§4Dimension Debug§f(§cComing Soon!§f)§b",
                icon: "textures/ui/NetherPortal",
                deprecated: true,
                experimental: false,
                unused: false,
                upcoming: true,
                functional: false,
                advanced: false,
                defaultButtonIndex: 16,
            },
            inventoryTransfer: {
                displayName: "Inventory Transfer§f(§nDEPRECATED§f)",
                icon: "textures/ui/NetherPortal",
                deprecated: true,
                experimental: false,
                unused: false,
                upcoming: false,
                functional: true,
                advanced: false,
                defaultButtonIndex: 16,
            },
            runCommand: {
                displayName: "Run Command",
                icon: "textures/ui/ImpulseSquare.png",
                deprecated: false,
                experimental: false,
                unused: false,
                upcoming: false,
                functional: true,
                advanced: false,
                defaultButtonIndex: 11,
            },
            scriptEval: {
                displayName: "Script Eval",
                icon: "textures/ui/RepeatSquare.png",
                deprecated: false,
                experimental: false,
                unused: false,
                upcoming: false,
                functional: true,
                advanced: false,
                defaultButtonIndex: 12,
            },
            manageRestrictedAreas: {
                displayName: "Mange Restricted Areas",
                icon: "textures/ui/xyz_axis.png",
                deprecated: false,
                experimental: false,
                unused: false,
                upcoming: false,
                functional: true,
                advanced: false,
                defaultButtonIndex: -7,
            },
            manageCustomUIs: {
                displayName: "Manage Custom UIs",
                icon: "textures/ui/feedIcon",
                deprecated: false,
                experimental: false,
                unused: false,
                upcoming: false,
                functional: true,
                advanced: false,
                defaultButtonIndex: -5,
            },
            moderation: {
                displayName: "Moderation",
                icon: "textures/ui/hammer_l",
                deprecated: false,
                experimental: false,
                unused: false,
                upcoming: false,
                functional: true,
                advanced: false,
                defaultButtonIndex: -9,
            },
            security: {
                displayName: "Security",
                icon: "textures/ui/absorption_effect",
                deprecated: false,
                experimental: false,
                unused: false,
                upcoming: false,
                functional: true,
                advanced: false,
                defaultButtonIndex: -8,
            },
            settings: {
                displayName: "Settings",
                icon: "textures/ui/settings_glyph_color_2x",
                deprecated: false,
                experimental: false,
                unused: false,
                upcoming: false,
                functional: true,
                advanced: false,
                defaultButtonIndex: -9999,
            },
            managePlayers: {
                displayName: "Manage Players",
                icon: "textures/ui/user_icon_white",
                deprecated: false,
                experimental: false,
                unused: false,
                upcoming: false,
                functional: true,
                advanced: false,
                defaultButtonIndex: -10,
            },
            manageCommands: {
                displayName: "Manage Commands",
                icon: "textures/ui/chat_keyboard_hover",
                deprecated: false,
                experimental: false,
                unused: false,
                upcoming: false,
                functional: true,
                advanced: false,
                defaultButtonIndex: -6,
            },
            itemEditor: {
                displayName: "§eItem Editor §f[§cAlpha§f]",
                icon: "textures/ui/icon_recipe_item",
                deprecated: false,
                experimental: true,
                unused: false,
                upcoming: false,
                functional: true,
                advanced: false,
                defaultButtonIndex: 25,
            },
            mapArtGnerator: {
                displayName: "§eMap Art Generator §f[§cAlpha§f]",
                icon: "textures/items/map_locked",
                deprecated: false,
                experimental: true,
                unused: false,
                upcoming: false,
                functional: true,
                advanced: false,
                defaultButtonIndex: 26,
            },
            javaNBTStructureLoader: {
                displayName: "§eJava NBT Structure Loader §f[§cAlpha§f]",
                icon: "textures/ui/xyz_axis",
                deprecated: false,
                experimental: true,
                unused: false,
                upcoming: false,
                functional: true,
                advanced: false,
                defaultButtonIndex: 27,
            },
        },
    },
    playerMenu: {
        paths: ["playerMenu"],
        supportedModes: {
            advanced: false,
            simple: false,
        },
        buttons: {
            leaderboards: {
                displayName: "Leaderboards",
                icon: "textures/ui/icon_best3", // textures/ui/trophy
                deprecated: false,
                experimental: false,
                unused: false,
                upcoming: false,
                functional: true,
                advanced: false,
                defaultButtonIndex: 0,
            },
            homes: {
                displayName: "Homes",
                icon: "textures/ui/store_home_icon",
                deprecated: false,
                experimental: false,
                unused: false,
                upcoming: false,
                functional: true,
                advanced: false,
                defaultButtonIndex: 1,
                extraVisibilityConditionsCheck: () => config.homeSystem.homeSystemEnabled,
                extraVisibilityConditionsCheckFailedReason() {
                    return "the home system is disabled";
                },
            },
            TPA: {
                displayName: "TPA",
                icon: "textures/ui/switch_accounts",
                deprecated: false,
                experimental: false,
                unused: false,
                upcoming: false,
                functional: true,
                advanced: false,
                defaultButtonIndex: 2,
                extraVisibilityConditionsCheck: () => config.tpaSystem.tpaSystemEnabled,
                extraVisibilityConditionsCheckFailedReason() {
                    return "the TPA system is disabled";
                },
            },
            warps: {
                displayName: "Warps",
                icon: "textures/items/ender_pearl",
                deprecated: false,
                experimental: false,
                unused: false,
                upcoming: false,
                functional: true,
                advanced: false,
                defaultButtonIndex: 3,
                extraVisibilityConditionsCheck: () => config.warpsSystem.enabled,
                extraVisibilityConditionsCheckFailedReason() {
                    return "the warps system is disabled";
                },
            },
            bounties: {
                displayName: "Bounties",
                icon: "textures/ui/strength_effect",
                deprecated: false,
                experimental: false,
                unused: false,
                upcoming: false,
                functional: true,
                advanced: false,
                defaultButtonIndex: 4,
                extraVisibilityConditionsCheck: () => config.bountySystem.enabled,
                extraVisibilityConditionsCheckFailedReason() {
                    return "the bounty system is disabled";
                },
            },
            serverShops: {
                displayName: "Server Shops",
                icon: "textures/ui/icon_deals",
                deprecated: false,
                experimental: false,
                unused: false,
                upcoming: false,
                functional: true,
                advanced: false,
                defaultButtonIndex: 5,
                extraVisibilityConditionsCheck: () => config.shopSystem.server.enabled,
                extraVisibilityConditionsCheckFailedReason() {
                    return "the server shop system is disabled";
                },
            },
            playerShops: {
                displayName: "Player Shops",
                icon: "textures/ui/icon_multiplayer",
                deprecated: false,
                experimental: false,
                unused: false,
                upcoming: false,
                functional: true,
                advanced: false,
                defaultButtonIndex: 5,
                extraVisibilityConditionsCheck: () => config.shopSystem.player.enabled,
                extraVisibilityConditionsCheckFailedReason() {
                    return "the player shop system is disabled";
                },
            },
            moneyTransfer: {
                displayName: "Money Transfer",
                icon: "textures/ui/trade_icon",
                deprecated: false,
                experimental: false,
                unused: false,
                upcoming: false,
                functional: true,
                advanced: false,
                defaultButtonIndex: 6,
                extraVisibilityConditionsCheck: () => config.moneyTransferSystem.enabled,
                extraVisibilityConditionsCheckFailedReason() {
                    return "the money transfer system is disabled";
                },
            },
            dailyRewards: {
                displayName: "Daily Rewards",
                icon: "textures/ui/inventory_icon",
                deprecated: false,
                experimental: false,
                unused: false,
                upcoming: true,
                functional: false,
                advanced: false,
                defaultButtonIndex: 7,
            },
            redeemCode: {
                displayName: "Redeem Code",
                icon: "textures/ui/icon_blackfriday",
                deprecated: false,
                experimental: false,
                unused: false,
                upcoming: false,
                functional: true,
                advanced: false,
                defaultButtonIndex: 8,
            },
            about: {
                displayName: "About",
                icon: "textures/ui/debug_sticks_pack_icon",
                deprecated: false,
                experimental: false,
                unused: false,
                upcoming: false,
                functional: true,
                advanced: false,
                defaultButtonIndex: 9,
            },
        },
    },
} as const satisfies menuButtonIdsType;
