import { Vector3Builder, Vector3Utils } from "@minecraft/math";
export declare class Vector extends Vector3Builder implements Vector3Utils {
    zero: import("@minecraft/server").Vector3;
    one: import("@minecraft/server").Vector3;
    up: import("@minecraft/server").Vector3;
    down: import("@minecraft/server").Vector3;
    north: import("@minecraft/server").Vector3;
    south: import("@minecraft/server").Vector3;
    east: import("@minecraft/server").Vector3;
    west: import("@minecraft/server").Vector3;
    right: import("@minecraft/server").Vector3;
    left: import("@minecraft/server").Vector3;
    back: import("@minecraft/server").Vector3;
    forward: import("@minecraft/server").Vector3;
    static zero: import("@minecraft/server").Vector3;
    static one: import("@minecraft/server").Vector3;
    static up: import("@minecraft/server").Vector3;
    static down: import("@minecraft/server").Vector3;
    static north: import("@minecraft/server").Vector3;
    static south: import("@minecraft/server").Vector3;
    static east: import("@minecraft/server").Vector3;
    static west: import("@minecraft/server").Vector3;
    static right: import("@minecraft/server").Vector3;
    static left: import("@minecraft/server").Vector3;
    static back: import("@minecraft/server").Vector3;
    static forward: import("@minecraft/server").Vector3;
    static add: typeof Vector3Utils.add;
    static clamp: typeof Vector3Utils.clamp;
    static cross: typeof Vector3Utils.cross;
    static distance: typeof Vector3Utils.distance;
    static dot: typeof Vector3Utils.dot;
    static equals: typeof Vector3Utils.equals;
    static floor: typeof Vector3Utils.floor;
    static lerp: typeof Vector3Utils.lerp;
    static magnitude: typeof Vector3Utils.magnitude;
    static normalize: typeof Vector3Utils.normalize;
    static scale: typeof Vector3Utils.scale;
    static slerp: typeof Vector3Utils.slerp;
    static subtract: typeof Vector3Utils.subtract;
}
