import { Player, type Vector3, Dimension, type Vector2, Block, Entity, type RawMessage, EntityInventoryComponent, EntityEquippableComponent, PlayerCursorInventoryComponent, ItemStack, ContainerSlot, type VectorYZ, type VectorXZ, EffectType, type EntityEffectOptions, type MusicOptions, type PlayerSoundOptions, GameMode, type DimensionLocation, MolangVariableMap, type EntityApplyDamageByProjectileOptions, type EntityApplyDamageOptions, type BlockRaycastOptions, type EntityComponentTypeMap, type BlockComponentTypeMap, type EntityRaycastOptions, type EntityQueryOptions, type PlayAnimationOptions, type TeleportOptions, InputInfo } from "@minecraft/server";
import { MoneySystem } from "ExtraFeatures/money";
import { PlayerNotifications } from "init/classes/PlayerNotifications";
import { PlayerPermissions } from "init/classes/PlayerPermissions";
import { WorldEditSelection } from "init/classes/WorldEditSelection";
import { WorldPosition } from "modules/coordinates/classes/WorldPosition";
import type { RotationLocation } from "modules/coordinates/interfaces/RotationLocation";
export declare class executeCommandPlayerW {
    player?: Player;
    sendErrorsTo?: Player | Console | Player[] | (() => Player | Player[] | Console) | null | undefined;
    modifiedlocation?: Vector3;
    modifieddimension?: Dimension;
    rotation?: Vector2;
    block?: Block;
    fromPlayer: boolean;
    fromEntity: boolean;
    isFromWorldPosition: boolean;
    fromPlayerWorldPosition: boolean;
    fromEntityWorldPosition: boolean;
    fromBlockWorldPosition: boolean;
    rawWorldPosition?: WorldPosition;
    raw?: any;
    constructor(player: Player | Entity | WorldPosition, sendErrorsTo?: Player | Console | null | number);
    toWorldPosition(): WorldPosition;
    run(command: string): void;
    sendError(error: any, sendErrorAsIs?: boolean, sendErrorsTo?: Player | Console | Player[] | (() => Player | Player[] | Console) | null | undefined): void;
    sendMessageB(message: string | RawMessage | (string | RawMessage)[], sendErrorsTo?: Player | Console | Player[] | (() => Player | Player[] | Console) | null | undefined): void;
    get inventory(): EntityInventoryComponent | undefined;
    get equippable(): EntityEquippableComponent | undefined;
    get cursorInventory(): PlayerCursorInventoryComponent | undefined;
    get heldItem(): ItemStack | undefined;
    get activeSlot(): ContainerSlot | undefined;
    get moneySystem(): MoneySystem;
    get playerNotifications(): PlayerNotifications;
    get playerPermissions(): PlayerPermissions;
    get worldEditSelection(): WorldEditSelection;
    get dimensionLocation(): Vector3 & {
        dimension: Dimension;
    };
    get dimension(): Dimension;
    get location(): Vector3;
    get locationstring(): `${number} ${number} ${number}`;
    get rotationstring(): `${number} ${number}`;
    get locationrotation(): RotationLocation;
    get directionvector(): Vector3;
    get xy(): Vector2;
    get yz(): VectorYZ;
    get xz(): VectorXZ;
    get chunkIndex(): VectorXZ;
    get x(): number;
    get y(): number;
    get z(): number;
    get rotx(): number;
    get roty(): number;
    get timeZone(): number;
    set timeZone(timezone: number | string | boolean | null | undefined);
    get camera(): import("@minecraft/server").Camera;
    get isEmoting(): boolean;
    get isFlying(): boolean;
    get isGliding(): boolean;
    get isJumping(): boolean;
    get isClimbing(): boolean;
    get isFalling(): boolean;
    get isInWater(): boolean;
    get isOnGround(): boolean;
    get isSleeping(): boolean;
    get isSprinting(): boolean;
    get isSwimming(): boolean;
    get scoreboardIdentity(): import("@minecraft/server").ScoreboardIdentity;
    get level(): number;
    get onScreenDisplay(): import("@minecraft/server").ScreenDisplay;
    get selectedSlotIndex(): number;
    set selectedSlotIndex(slotNumber: number);
    get totalXpNeededForNextLevel(): number;
    get xpEarnedAtCurrentLevel(): number;
    get isSneaking(): boolean;
    set isSneaking(isSneaking: boolean);
    get typeId(): string;
    get nameTag(): string | undefined | null;
    set nameTag(nameTag: string | undefined | null);
    get inputPermissions(): import("@minecraft/server").PlayerInputPermissions;
    get clientSystemInfo(): import("@minecraft/server").ClientSystemInfo;
    get inputInfo(): InputInfo;
    addEffect(effectType: string | EffectType, duration: number, options?: EntityEffectOptions): import("@minecraft/server").Effect;
    addExperience(amount: number): number;
    getRotation(): Vector2;
    getViewDirection(): Vector3;
    addLevels(amount: number): number;
    eatItem(itemStack: ItemStack): void;
    getGameMode(): GameMode;
    getItemCooldown(itemCategory: string): number;
    getSpawnPoint(): DimensionLocation;
    getTotalXp(): number;
    isOp(): boolean;
    lookAt(targetLocation: Vector3): void;
    playMusic(trackId: string, musicOptions?: MusicOptions): void;
    playSound(soundId: string, soundOptions?: PlayerSoundOptions): void;
    postClientMessage(id: string, value: string): void;
    queueMusic(trackId: string, musicOptions?: MusicOptions): void;
    resetLevel(): void;
    sendMessage(message: string | RawMessage | (string | RawMessage)[]): void;
    setGameMode(gameMode?: GameMode): void;
    setOp(isOp: boolean): void;
    setSpawnPoint(spawnPoint?: DimensionLocation): void;
    spawnParticle(effectName: string, location: Vector3, molangVariables?: MolangVariableMap): void;
    startItemCooldown(itemCategory: string, tickDuration: number): void;
    stopMusic(): void;
    addTag(tag: string): boolean;
    applyDamage(amount: number, options?: EntityApplyDamageByProjectileOptions | EntityApplyDamageOptions): boolean;
    applyImpulse(vector: Vector3): void;
    applyKnockback(directionX: number, directionZ: number, horizontalStrength: number, verticalStrength: number): void;
    clearDynamicProperties(): void;
    clearVelocity(): void;
    extinguishFire(useEffects?: boolean): boolean;
    getAimAssist(): import("@minecraft/server").PlayerAimAssist;
    getBlockFromViewDirection(options?: BlockRaycastOptions): import("@minecraft/server").BlockRaycastHit;
    getComponent<T extends keyof EntityComponentTypeMap>(componentId: T): EntityComponentTypeMap[T] | undefined;
    getComponent<T extends keyof BlockComponentTypeMap>(componentId: T): BlockComponentTypeMap[T] | undefined;
    getComponents(): import("@minecraft/server").EntityComponent[];
    getDynamicProperty(identifier: string): string | number | boolean | Vector3;
    getDynamicPropertyIds(): string[];
    getDynamicPropertyTotalByteCount(): number;
    getEffect(effectType: string | EffectType): import("@minecraft/server").Effect;
    getEffects(): import("@minecraft/server").Effect[];
    getEntitiesFromViewDirection(options?: EntityRaycastOptions): import("@minecraft/server").EntityRaycastHit[];
    getHeadLocation(): Vector3;
    getProperty(identifier: string): string | number | boolean;
    getTags(): string[];
    getVelocity(): Vector3;
    hasComponent(componentId: string): boolean;
    hasTag(tag: string): boolean;
    isValid(): boolean;
    kill(): boolean;
    matches(options: EntityQueryOptions): boolean;
    playAnimation(animationName: string, options?: PlayAnimationOptions): void;
    remove(): void;
    removeEffect(effectType: string | EffectType): boolean;
    removeTag(tag: string): boolean;
    resetProperty(identifier: string): string | number | boolean;
    runCommand(commandString: string): import("@minecraft/server").CommandResult;
    runCommandAsync(commandString: string): Promise<import("@minecraft/server").CommandResult>;
    setDynamicProperty(identifier: string, value?: string | number | boolean | Vector3): void;
    setDynamicProperties(values: Record<string, boolean | number | string | Vector3>): void;
    setOnFire(seconds: number, useEffects?: boolean): boolean;
    setProperty(identifier: string, value: string | number | boolean): void;
    setRotation(rotation: Vector2): void;
    teleport(location: Vector3, teleportOptions?: TeleportOptions): void;
    triggerEvent(eventName: string): void;
    tryTeleport(location: Vector3, teleportOptions?: TeleportOptions): boolean;
    saveStringToDynamicProperties(string: string, propertyName: string, clearOldProperties?: boolean, chunkSize?: number | bigint): void;
    getStringFromDynamicProperties(propertyName: string, zeroLengthPlaceholder?: string): string;
}
