import type { ItemLockMode, Enchantment, DimensionLocation, Entity, Vector3 } from "@minecraft/server";
export interface ItemJSONParseInput {
    name?: string;
    "minecraft:name"?: string;
    nameTag?: string;
    "minecraft:nameTag"?: string;
    lore?: string[];
    "minecraft:lore"?: string[];
    description?: string[];
    "minecraft:description"?: string[];
    count?: number;
    "minecraft:count"?: number;
    amount?: number;
    "minecraft:amount"?: number;
    keepOnDeath?: boolean;
    "minecraft:keepOnDeath"?: boolean;
    keepondeath?: boolean;
    "minecraft:keepondeath"?: boolean;
    keep_on_death?: boolean;
    "minecraft:keep_on_death"?: boolean;
    lockMode?: ItemLockMode;
    "minecraft:lockMode"?: ItemLockMode;
    lockmode?: ItemLockMode;
    "minecraft:lockmode"?: ItemLockMode;
    lock_mode?: ItemLockMode;
    "minecraft:lock_mode"?: ItemLockMode;
    itemLockMode?: ItemLockMode;
    "minecraft:itemLockMode"?: ItemLockMode;
    itemlockmode?: ItemLockMode;
    "minecraft:itemlockmode"?: ItemLockMode;
    item_lock_mode?: ItemLockMode;
    "minecraft:item_lock_mode"?: ItemLockMode;
    canPlaceOn?: string[];
    "minecraft:canPlaceOn"?: string[];
    canplaceon?: string[];
    "minecraft:canplaceon"?: string[];
    can_place_on?: string[];
    "minecraft:can_place_on"?: string[];
    canDestroy?: string[];
    "minecraft:canDestroy"?: string[];
    candestroy?: string[];
    "minecraft:candestroy"?: string[];
    can_destroy?: string[];
    "minecraft:can_destroy"?: string[];
    components?: {
        enchantable?: {
            add?: Enchantment | Enchantment[];
            "minecraft:add"?: Enchantment | Enchantment[];
            addEnchantment?: Enchantment | Enchantment[];
            "minecraft:addEnchantment"?: Enchantment | Enchantment[];
            addList?: Enchantment[];
            "minecraft:addList"?: Enchantment[];
            addEnchantments?: Enchantment[];
            "minecraft:addEnchantments"?: Enchantment[];
            remove?: Enchantment;
            "minecraft:remove"?: Enchantment;
            removeEnchantments?: Enchantment;
            "minecraft:removeEnchantments"?: Enchantment;
            clear?: any;
            "minecraft:clear"?: any;
            clearAll?: any;
            "minecraft:clearAll"?: any;
            removeAll?: any;
            "minecraft:removeAll"?: any;
            removeAllEnchantments?: any;
            "minecraft:removeAllEnchantments"?: any;
        };
        "minecraft:enchantable"?: {
            add?: Enchantment | Enchantment[];
            "minecraft:add"?: Enchantment | Enchantment[];
            addEnchantment?: Enchantment | Enchantment[];
            "minecraft:addEnchantment"?: Enchantment | Enchantment[];
            addList?: Enchantment[];
            "minecraft:addList"?: Enchantment[];
            addEnchantments?: Enchantment[];
            "minecraft:addEnchantments"?: Enchantment[];
            remove?: Enchantment;
            "minecraft:remove"?: Enchantment;
            removeEnchantments?: Enchantment;
            "minecraft:removeEnchantments"?: Enchantment;
            clear?: any;
            "minecraft:clear"?: any;
            clearAll?: any;
            "minecraft:clearAll"?: any;
            removeAll?: any;
            "minecraft:removeAll"?: any;
            removeAllEnchantments?: any;
            "minecraft:removeAllEnchantments"?: any;
        };
        durability?: {
            durability?: number;
            "minecraft:durability"?: number;
            setDurability?: number;
            "minecraft:setDurability"?: number;
            damage?: number;
            "minecraft:damage"?: number;
            setDamage?: number;
            "minecraft:setDamage"?: number;
            repair?: number;
            "minecraft:repair"?: number;
            setDurabilityToMax?: any;
            "minecraft:setDurabilityToMax"?: any;
        };
        "minecraft:durability"?: {
            durability?: number;
            "minecraft:durability"?: number;
            setDurability?: number;
            "minecraft:setDurability"?: number;
            damage?: number;
            "minecraft:damage"?: number;
            setDamage?: number;
            "minecraft:setDamage"?: number;
            repair?: number;
            "minecraft:repair"?: number;
            setDurabilityToMax?: any;
            "minecraft:setDurabilityToMax"?: any;
        };
        damage?: {
            durability?: number;
            "minecraft:durability"?: number;
            setDurability?: number;
            "minecraft:setDurability"?: number;
            damage?: number;
            "minecraft:damage"?: number;
            setDamage?: number;
            "minecraft:setDamage"?: number;
            repair?: number;
            "minecraft:repair"?: number;
            setDurabilityToMax?: any;
            "minecraft:setDurabilityToMax"?: any;
        };
        "minecraft:damage"?: {
            durability?: number;
            "minecraft:durability"?: number;
            setDurability?: number;
            "minecraft:setDurability"?: number;
            damage?: number;
            "minecraft:damage"?: number;
            setDamage?: number;
            "minecraft:setDamage"?: number;
            repair?: number;
            "minecraft:repair"?: number;
            setDurabilityToMax?: any;
            "minecraft:setDurabilityToMax"?: any;
        };
        cooldown?: any;
        "minecraft:cooldown"?: any;
        food?: any;
        "minecraft:food"?: any;
    };
    "minecraft:components"?: {
        enchantable?: {
            add?: Enchantment | Enchantment[];
            "minecraft:add"?: Enchantment | Enchantment[];
            addEnchantment?: Enchantment | Enchantment[];
            "minecraft:addEnchantment"?: Enchantment | Enchantment[];
            addList?: Enchantment[];
            "minecraft:addList"?: Enchantment[];
            addEnchantments?: Enchantment[];
            "minecraft:addEnchantments"?: Enchantment[];
            remove?: Enchantment;
            "minecraft:remove"?: Enchantment;
            removeEnchantments?: Enchantment;
            "minecraft:removeEnchantments"?: Enchantment;
            clear?: any;
            "minecraft:clear"?: any;
            clearAll?: any;
            "minecraft:clearAll"?: any;
            removeAll?: any;
            "minecraft:removeAll"?: any;
            removeAllEnchantments?: any;
            "minecraft:removeAllEnchantments"?: any;
        };
        "minecraft:enchantable"?: {
            add?: Enchantment | Enchantment[];
            "minecraft:add"?: Enchantment | Enchantment[];
            addEnchantment?: Enchantment | Enchantment[];
            "minecraft:addEnchantment"?: Enchantment | Enchantment[];
            addList?: Enchantment[];
            "minecraft:addList"?: Enchantment[];
            addEnchantments?: Enchantment[];
            "minecraft:addEnchantments"?: Enchantment[];
            remove?: Enchantment;
            "minecraft:remove"?: Enchantment;
            removeEnchantments?: Enchantment;
            "minecraft:removeEnchantments"?: Enchantment;
            clear?: any;
            "minecraft:clear"?: any;
            clearAll?: any;
            "minecraft:clearAll"?: any;
            removeAll?: any;
            "minecraft:removeAll"?: any;
            removeAllEnchantments?: any;
            "minecraft:removeAllEnchantments"?: any;
        };
        durability?: {
            durability?: number;
            "minecraft:durability"?: number;
            setDurability?: number;
            "minecraft:setDurability"?: number;
            damage?: number;
            "minecraft:damage"?: number;
            setDamage?: number;
            "minecraft:setDamage"?: number;
            repair?: number;
            "minecraft:repair"?: number;
            setDurabilityToMax?: any;
            "minecraft:setDurabilityToMax"?: any;
        };
        "minecraft:durability"?: {
            durability?: number;
            "minecraft:durability"?: number;
            setDurability?: number;
            "minecraft:setDurability"?: number;
            damage?: number;
            "minecraft:damage"?: number;
            setDamage?: number;
            "minecraft:setDamage"?: number;
            repair?: number;
            "minecraft:repair"?: number;
            setDurabilityToMax?: any;
            "minecraft:setDurabilityToMax"?: any;
        };
        damage?: {
            durability?: number;
            "minecraft:durability"?: number;
            setDurability?: number;
            "minecraft:setDurability"?: number;
            damage?: number;
            "minecraft:damage"?: number;
            setDamage?: number;
            "minecraft:setDamage"?: number;
            repair?: number;
            "minecraft:repair"?: number;
            setDurabilityToMax?: any;
            "minecraft:setDurabilityToMax"?: any;
        };
        "minecraft:damage"?: {
            durability?: number;
            "minecraft:durability"?: number;
            setDurability?: number;
            "minecraft:setDurability"?: number;
            damage?: number;
            "minecraft:damage"?: number;
            setDamage?: number;
            "minecraft:setDamage"?: number;
            repair?: number;
            "minecraft:repair"?: number;
            setDurabilityToMax?: any;
            "minecraft:setDurabilityToMax"?: any;
        };
        cooldown?: any;
        "minecraft:cooldown"?: any;
        food?: any;
        "minecraft:food"?: any;
    };
    force?: boolean;
    source?: {
        type?: string;
        targetSelector?: string;
        targetSelectorExecutionLocation?: DimensionLocation;
        targetSelectorSourceEntity?: Entity;
        player?: string;
        entityAtBlock?: DimensionLocation;
        entityType?: string;
        entityTypeId?: string;
        entityId?: string | number;
        block?: DimensionLocation;
        slot?: number;
        id?: string;
        itemId?: string;
        count?: number;
        amount?: number;
    };
    type?: string;
    id?: string;
    itemId?: string;
    new?: [string, number?];
    dynamicProperties?: [string, string | number | boolean | Vector3 | undefined][] | Record<string, string | number | boolean | Vector3 | undefined> | {
        [k: string]: string | number | boolean | Vector3 | undefined;
    };
    dynamicproperties?: [string, string | number | boolean | Vector3 | undefined][] | Record<string, string | number | boolean | Vector3 | undefined> | {
        [k: string]: string | number | boolean | Vector3 | undefined;
    };
    properties?: [string, string | number | boolean | Vector3 | undefined][] | Record<string, string | number | boolean | Vector3 | undefined> | {
        [k: string]: string | number | boolean | Vector3 | undefined;
    };
    itemproperties?: [string, string | number | boolean | Vector3 | undefined][] | Record<string, string | number | boolean | Vector3 | undefined> | {
        [k: string]: string | number | boolean | Vector3 | undefined;
    };
    itemProperties?: [string, string | number | boolean | Vector3 | undefined][] | Record<string, string | number | boolean | Vector3 | undefined> | {
        [k: string]: string | number | boolean | Vector3 | undefined;
    };
    clearAllDynamicProperties?: any;
    clearDynamicProperties?: any;
    clearalldynamicproperties?: any;
    cleardynamicproperties?: any;
    removeDynamicProperties?: string[];
    removedynamicproperties?: string[];
    removeDynamicProperty?: string;
    removedynamicproperty?: string;
    "minecraft:dynamicProperties"?: [string, string | number | boolean | Vector3 | undefined][] | Record<string, string | number | boolean | Vector3 | undefined> | {
        [k: string]: string | number | boolean | Vector3 | undefined;
    };
    "minecraft:dynamicproperties"?: [string, string | number | boolean | Vector3 | undefined][] | Record<string, string | number | boolean | Vector3 | undefined> | {
        [k: string]: string | number | boolean | Vector3 | undefined;
    };
    "minecraft:properties"?: [string, string | number | boolean | Vector3 | undefined][] | Record<string, string | number | boolean | Vector3 | undefined> | {
        [k: string]: string | number | boolean | Vector3 | undefined;
    };
    "minecraft:itemProperties"?: [string, string | number | boolean | Vector3 | undefined][] | Record<string, string | number | boolean | Vector3 | undefined> | {
        [k: string]: string | number | boolean | Vector3 | undefined;
    };
    "minecraft:itemproperties"?: [string, string | number | boolean | Vector3 | undefined][] | Record<string, string | number | boolean | Vector3 | undefined> | {
        [k: string]: string | number | boolean | Vector3 | undefined;
    };
    "minecraft:clearAllDynamicProperties"?: any;
    "minecraft:clearDynamicProperties"?: any;
    "minecraft:clearalldynamicproperties"?: any;
    "minecraft:cleardynamicproperties"?: any;
    "minecraft:removeDynamicProperties"?: string[];
    "minecraft:removedynamicproperties"?: string[];
    "minecraft:removeDynamicProperty"?: string;
    "minecraft:removedynamicproperty"?: string;
}
