export declare const patternFunctionList: {
    rainbow: (ib: number) => string | undefined;
    randomrainbow: (ib: number, offset: number) => string | undefined;
    shuffledrainbow: () => string | undefined;
    bluegradient: (ib: number) => string | undefined;
    randombluegradient: (ib: number, offset: number) => string | undefined;
    shuffledbluegradient: () => string | undefined;
    yellowgradient: (ib: number) => string | undefined;
    randomyellowgradient: (ib: number, offset: number) => string | undefined;
    shuffledyellowgradient: () => string | undefined;
    blackgradient: (ib: number) => string | undefined;
    randomblackgradient: (ib: number, offset: number) => string | undefined;
    shuffledblackgradient: () => string | undefined;
    graygradient: (ib: number) => string | undefined;
    randomgraygradient: (ib: number, offset: number) => string | undefined;
    shuffledgraygradient: () => string | undefined;
    purplegradient: (ib: number) => string | undefined;
    randompurplegradient: (ib: number, offset: number) => string | undefined;
    shuffledpurplegradient: () => string | undefined;
};
