export const JunkItemTypes = [
    "dirt",
    "stick",
    "deadbush",
    "tripwire_hook",
    "rotten_flesh",
    "string",
    "cobblestone",
    "stone",
    "diorite",
    "andesite",
    "granite",
    "tuff",
    "end_stone",
    "wheat_seeds",
    "tallgrass",
    "leather_helmet",
    "leather_boots",
    "leather_chestplate",
    "leather_leggings",
    "wooden_sword",
    "wooden_axe",
    "wooden_pickaxe",
    "wooden_shovel",
    "wooden_hoe",
    "spider_eye",
];
//# sourceMappingURL=JunkItemTypes.js.map