export const OpItemTypes = [
    "diamond",
    "netherite_ingot",
    "gold_ingot",
    "iron_ingot",
    "diamond_sword",
    "diamond_chestplate",
    "diamond_helmet",
    "diamond_leggings",
    "diamond_boots",
    "diamond_pickaxe",
    "diamond_shovel",
    "diamond_hoe",
    "diamond_block",
];
